# Generated by Django 5.2.5 on 2025-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=7)),
                ("disponible", models.BooleanField(default=True)),
            ],
        ),
    ]
