# Generated by Django 5.2.5 on 2025-08-26 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzeria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
