# Generated by Django 5.2.5 on 2025-08-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzeria", "0002_pizza_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "allergens",
                    models.CharField(
                        blank=True,
                        help_text="gluten, lactose, oeufs, soja, etc.",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auteur", models.CharField(max_length=120)),
                ("texte", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="pizzeria.pizza",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pizza",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ingrédients composant la pizza",
                related_name="pizzas",
                to="pizzeria.ingredient",
            ),
        ),
    ]
